{{ range .Values.instances }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lightsout.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "lightsout.name" $ }}-{{ .name }}
spec:
{{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lightsout.name" $ }}-{{ .name }}
  template:
    metadata:
    {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "lightsout.name" $ }}-{{ .name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lightsout.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}-{{ .name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ .image }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
---
{{end}}
